#ifndef MAKE_ME_LAUGH_GLOBAL_H
#define MAKE_ME_LAUGH_GLOBAL_H

#define ROPE_LENGTH 8
#define PLAYER_COUNT 2

#define PLAYER_PALETTE PAL1
#define BALL_PALETTE PAL2
#define ROPE_PALETTE PAL3

#endif //MAKE_ME_LAUGH_GLOBAL_H
